name: "Dockstore WDL Action"
description: "Set up Dockstore CLI and test WDL files"
author: "GKS-AnVIL"
inputs:
  wdl_file:
    description: "Path to the WDL file to test"
    required: true
  test_parameters:
    description: "Path to JSON declaration of parameters for test arguments"
    required: false
outputs:
  result:
    description: "Test results"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DOCKSTORE_ROOT: true
  args:
    - ${{ inputs.wdl_file }}
    - ${{ inputs.test_parameters }}
