name: Test action

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Dockstore WDL Action
      uses: ./
      with:
        wdl_file: "tests/fixtures/workflow.wdl"
        test_parameters: "tests/fixtures/parameters.json"
